<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>062eec3d-d9d6-48d6-b818-86e088b7fce4</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0"/>
        <PackageReference Include="Aspire.Hosting.Azure.KeyVault" Version="9.0.0" />
        <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="9.0.0" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.0.0" />
        <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="9.0.0" />
        <PackageReference Include="HotChocolate.Fusion.Aspire" Version="14.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Frontends\FamilieLaissFrontend\FamilieLaissFrontend\FamilieLaissFrontend.csproj" />
      <ProjectReference Include="..\..\Gateways\SPAGateway\SPAGateway.csproj" />
      <ProjectReference Include="..\..\Services\Catalog\Catalog.API\Catalog.API.csproj" />
      <ProjectReference Include="..\..\Services\Google\Google.API\Google.API.csproj" />
      <ProjectReference Include="..\..\Services\Settings\Settings.API\Settings.API.csproj" />
      <ProjectReference Include="..\..\Services\Upload\Upload.API\Upload.API.csproj" />
      <ProjectReference Include="..\..\Services\UserInteraction\UserInteraction.API\UserInteraction.API.csproj" />
      <ProjectReference Include="..\..\Services\User\User.API\User.API.csproj" />
    </ItemGroup>

</Project>
