// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserInteraction.Infrastructure.DBContext;

#nullable disable

namespace UserInteraction.Infrastructure.Migrations
{
    [DbContext(typeof(UserInteractionServiceDBContext))]
    [Migration("20250123153812_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("SequenceComment")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SequenceFavorite")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SequenceMediaItem")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SequenceRating")
                .IncrementsBy(10);

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "SequenceComment");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserInteractionInfoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserInteractionInfoId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.Favorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "SequenceFavorite");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserInteractionInfoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserInteractionInfoId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.MediaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "SequenceMediaItem");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "SequenceRating");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserInteractionInfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserInteractionInfoId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.UserInteractionInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("UserInteractionInfos");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.Comment", b =>
                {
                    b.HasOne("UserInteraction.Domain.Aggregates.MediaItem", "MediaItem")
                        .WithMany("Comments")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserInteraction.Domain.Aggregates.UserInteractionInfo", "UserInteractionInfo")
                        .WithMany("Comments")
                        .HasForeignKey("UserInteractionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("UserInteractionInfo");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.Favorite", b =>
                {
                    b.HasOne("UserInteraction.Domain.Aggregates.MediaItem", "MediaItem")
                        .WithMany("Favorites")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserInteraction.Domain.Aggregates.UserInteractionInfo", "UserInteractionInfo")
                        .WithMany("Favorites")
                        .HasForeignKey("UserInteractionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("UserInteractionInfo");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.Rating", b =>
                {
                    b.HasOne("UserInteraction.Domain.Aggregates.MediaItem", "MediaItem")
                        .WithMany("Ratings")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserInteraction.Domain.Aggregates.UserInteractionInfo", "UserInteractionInfo")
                        .WithMany("Ratings")
                        .HasForeignKey("UserInteractionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("UserInteractionInfo");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.UserInteractionInfo", b =>
                {
                    b.HasOne("UserInteraction.Domain.Aggregates.UserAccount", "UserAccount")
                        .WithOne("UserInteractionInfo")
                        .HasForeignKey("UserInteraction.Domain.Aggregates.UserInteractionInfo", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.MediaItem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.UserAccount", b =>
                {
                    b.Navigation("UserInteractionInfo");
                });

            modelBuilder.Entity("UserInteraction.Domain.Aggregates.UserInteractionInfo", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
