//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catalog.API.Resources.MessageText", typeof(MessageText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} photos have been added to the album &quot;{1}&quot;..
        /// </summary>
        public static string MediaItems_Photo_Added_Plural_English {
            get {
                return ResourceManager.GetString("MediaItems_Photo_Added_Plural_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden {0} Photos zum Album &quot;{1}&quot; hinzugefügt..
        /// </summary>
        public static string MediaItems_Photo_Added_Plural_German {
            get {
                return ResourceManager.GetString("MediaItems_Photo_Added_Plural_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 photo has been added to the album &quot;{0}&quot;..
        /// </summary>
        public static string MediaItems_Photo_Added_Single_English {
            get {
                return ResourceManager.GetString("MediaItems_Photo_Added_Single_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde 1 Photo zum Album &quot;{0}&quot; hinzugefügt..
        /// </summary>
        public static string MediaItems_Photo_Added_Single_German {
            get {
                return ResourceManager.GetString("MediaItems_Photo_Added_Single_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} videos have been added to the album &quot;{1}&quot;..
        /// </summary>
        public static string MediaItems_Video_Added_Plural_English {
            get {
                return ResourceManager.GetString("MediaItems_Video_Added_Plural_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden {0} Videos zum Album &quot;{1}&quot; hinzugefügt..
        /// </summary>
        public static string MediaItems_Video_Added_Plural_German {
            get {
                return ResourceManager.GetString("MediaItems_Video_Added_Plural_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 video has been added to the album &quot;{0}&quot;..
        /// </summary>
        public static string MediaItems_Video_Added_Single_English {
            get {
                return ResourceManager.GetString("MediaItems_Video_Added_Single_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde 1 Video zum Album &quot;{0}&quot; hinzugefügt..
        /// </summary>
        public static string MediaItems_Video_Added_Single_German {
            get {
                return ResourceManager.GetString("MediaItems_Video_Added_Single_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New photo album &quot;{0}&quot; was created..
        /// </summary>
        public static string NewAlbum_Photo_Created_English {
            get {
                return ResourceManager.GetString("NewAlbum_Photo_Created_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Photo-Album &quot;{0}&quot; wurde erstellt..
        /// </summary>
        public static string NewAlbum_Photo_Created_German {
            get {
                return ResourceManager.GetString("NewAlbum_Photo_Created_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New video album &quot;{0}&quot; was created..
        /// </summary>
        public static string NewAlbum_Video_Created_English {
            get {
                return ResourceManager.GetString("NewAlbum_Video_Created_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Video-Album &quot;{0}&quot; wurde erstellt..
        /// </summary>
        public static string NewAlbum_Video_Created_German {
            get {
                return ResourceManager.GetString("NewAlbum_Video_Created_German", resourceCulture);
            }
        }
    }
}
